(function(){function p(a,b,d){a&&(document.addEventListener?a.addEventListener(b,d,!1):a.attachEvent("on"+b,d))}function u(a,b,d){for(var f=[],a=document.getElementsByTagName(a),e=0,k=a.length;e<k;e++)for(var j=a[e],i=b,c=d,g=f,h=j.attributes,m=0,n=h.length;m<n;m++){var l=h[m],o=l.nodeValue;l.nodeName===i&&o===c&&g.push(j)}return f}function q(){var a,b,d=document.scripts;d||(d=document.querySelectorAll("script"));for(var f=0;f<d.length;f++)if(a=d[f].src,-1!==a.indexOf("share.js")&&(b=a.indexOf("/js/external/share.js"),
-1!==b))return a.substring(0,b);else return 'https://www.xing-share.com';}function r(a,b,d,f){a.setAttribute("src",q()+"/img/sections/share/"+b);a.setAttribute("border",0);a.setAttribute("width",d);a.setAttribute("height",f)}function A(){s=!0}function B(a){a||(a=window.event);a.cancelBubble=!0;a.stopPropagation&&a.stopPropagation();t&&clearTimeout(t)}function C(){t=setTimeout(function(){for(var a=0;a<n.length;a++){var b=n[a];b.nextSibling&&"xing-statistics-hovercard"==b.nextSibling.className&&b.parentNode.removeChild(b.nextSibling)}},250)}
function l(){var a=encodeURIComponent(window.location.href),b;b="querySelectorAll"in document?document.querySelectorAll('script[type="XING/Share"]'):u("script","type","XING/Share");for(var d=0,f=b.length;d<f;d++){var e=b[d],k=e.getAttribute("data-counter"),j=e.getAttribute("data-button-shape")||"rectangle",i=e.getAttribute("data-lang"),c=e.getAttribute("data-url"),g=a;c&&(g=encodeURIComponent(c));g=g.split("%");for(c=0;c<g.length;c++)g[c]=g[c].substring(0,2).toLowerCase()+g[c].substring(2);g=g.join("%");
if("no_count"===k){if(k=g,j){var g=e.parentNode,c=document.createElement("img"),h=document.createElement("a");switch(j){case "small_square":r(c,"share_button_16x16_v1.png","16","16");break;case "square":r(c,"share_button_32x32_v1.png","32","32");break;case "rectangle":r(c,"share_button_v1.png","55","20")}h.setAttribute("href",q()+"/app/user?op=share;sc_p=xing-share;url="+k);h.setAttribute("target","_blank");h.setAttribute("title","de"==i?"Meinen Kontakten auf XING empfehlen":"Share with my contacts on XING");
p(h,"click",A);h.appendChild(c);g.replaceChild(h,e)}}else{var c=k,h=i,m=j,j=c+"_"+m,i=document.createElement("iframe"),k=e.parentNode,l=q()+"/app/share?op=get_share_button";v++;g=[l,";url=",g,";counter=",c,";lang=",h,";type=iframe;hovercard_position=",v,";shape=",m].join("");c={right_rectangle:{width:161,height:20},right_square:{width:126,height:20},top_rectangle:{width:55,height:62}};h=document.createElement("div");m=["position:relative;height:",c[j].height,"px;width:",c[j].width,"px;"].join("");
w&&(m+="overflow:hidden;");h.setAttribute("style",m);p(h,"mouseover",B);i.setAttribute("style","padding:0px !important;border:none !important;margin:0px !important;overflow:hidden !important;background-color:transparent !important;width:"+c[j].width+"px !important;height:"+c[j].height+"px !important;");i.setAttribute("scrolling","no");i.setAttribute("height",c[j].height);i.setAttribute("src",g);i.setAttribute("width",c[j].width);i.setAttribute("class","XING");i.setAttribute("frameBorder","0");i.setAttribute("allowtransparency",
"true");n.push(i);h.appendChild(i);k.replaceChild(h,e)}}p(document,"mouseover",C)}function x(){if(!o){try{document.documentElement.doScroll("left")}catch(a){setTimeout(x,1);return}l()}}function y(a){var b,d;if(!(w||"string"!==typeof a.data)){d=a.data.split("|");a=d[0];b=d[1];d=d[2];var f;a:{for(f=0;f<n.length;f++)if(a===n[f].src){f=!0;break a}f=!1}if(f)for(f=0;f<n.length;f++){var e;e=n[f];var k=e.parentNode;if(e.src===a){e=document.createElement("div");e.setAttribute("class","xing-statistics-hovercard");
switch(b){case "right":e.setAttribute("style","position:absolute;top:0px;z-index:1000000;left:58px;");break;case "right_square":e.setAttribute("style","position:absolute;top:0px;z-index:1000000;left:24px;");break;case "top":e.setAttribute("style","position:absolute;top:0px;z-index:1000000;left:57px;")}e.innerHTML=d;k&&1==k.childNodes.length&&k.appendChild(e)}}}}var s=!1,o=!1,v=0,n=[],t,w=-1!==navigator.userAgent.indexOf("MSIE 7")||-1!==navigator.userAgent.indexOf("MSIE 6");"complete"===document.readyState&&
(o=!0,setTimeout(l,1));if(document.addEventListener)document.addEventListener("DOMContentLoaded",function(){o=true;l()},!1),window.addEventListener("load",function(){o=true;l()},!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",function(){o=true;l()});window.attachEvent("onload",function(){o=true;l()});var z=!1;try{z=null==window.frameElement}catch(D){}document.documentElement.doScroll&&z&&x()}window.onfocus=function(){if(s){var a=false in document?document.querySelectorAll('iframe[class="XING"]'):
u("iframe","class","XING"),b=0,d=a.length;for(;b<d;b++)a[b].src=a[b].src;s=false}};window.addEventListener?addEventListener("message",y,!1):attachEvent("onmessage",y)})();